on:
  push:
    branches: [main]
  workflow_dispatch:

name: Check rules

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

  main-branch:
    needs: setup
    runs-on: ubuntu-latest
    name: main-branch
    steps:
      - name: Install
        run: uv sync --all-extras --dev

      - name: Check for main branch as default
        run: uv run repository.py

  codeowners:
    needs: setup
    runs-on: ubuntu-latest
    name: codeowners
    steps:
      - name: Install
        run: uv sync --all-extras --dev

      - name: Check for codeowners file
        run: uv run codeowners.py
