on:
  push:
    branches: [main]
  workflow_dispatch:

name: Check rules

jobs:
  check-rules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    strategy:
      fail-fast: false
      matrix:
        rule: ["main_branch_default.py", "codeowners.py"]
    name: Rule ${{ matrix.rule }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Rule check
        run: uv run ${{ matrix.rule }}
